name: Deploy Default Sentinel Content

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run default Sentinel deploy script
      uses: azure/powershell@v2
      with:
        inlineScript: |
          # Wechsle ins Repo‑Verzeichnis
          Set-Location ${{ github.workspace }}

          # Führe das offizielle Deploy‑Script aus,
          # es liest automatisch sentinel-deployment.config
          ./.script/deploy.ps1 `
            -ConfigurationPath "${{ github.workspace }}/sentinel-deployment.config" `
            -RepositoryPath "${{ github.workspace }}" `
            -SubscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }} `
            -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP }} `
            -WorkspaceName ${{ secrets.AZURE_WORKSPACE_NAME }}
        azPSVersion: latest
        enable-AzPSSession: true
