# .github/workflows/sentinel-deploy.yml

name: Custom Sentinel Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Sentinel Deployment
        uses: azure/powershell@v2
        continue-on-error: true
        with:
          inlineScript: |
            Set-Location "${{ github.workspace }}"

            $config = "${{ github.workspace }}/sentinel-deployment.config"
            $repo   = "${{ github.workspace }}"
            $sub   = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            $rg    = "${{ secrets.AZURE_RESOURCE_GROUP }}"
            $ws    = "${{ secrets.AZURE_WORKSPACE_NAME }}"

            # Workaround: Lade das Deployment-Skript aus offiziellem Repo
            Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/scripts/deploy/deploy.ps1" -OutFile "deploy.ps1"
            
            # Deployment
            ./deploy.ps1 `
              -ConfigurationPath $config `
              -RepositoryPath $repo `
              -SubscriptionId $sub `
              -ResourceGroupName $rg `
              -WorkspaceName $ws `
              -ContinueOnError
          azPSVersion: 'latest'
          enable-AzPSSession: true
