name: Deploy Sentinel Content

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Azure-Anmeldung per OIDC
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3) PowerShell-Skript ausführen (dein sen.ps1)
      - name: Run Sentinel Deployment Script
        uses: azure/powershell@v2
        with:
          inlineScript: |
            # sicherstellen, dass wir im Repo-Root sind
            Set-Location ${{ github.workspace }}

            # Deployment starten
            ./scripts/sen.ps1 `
              -SubscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }} `
              -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP }} `
              -WorkspaceName ${{ secrets.AZURE_WORKSPACE_NAME }} `
              -RepoPath ${{ github.workspace }}
          # hier kannst du eine feste Az‑Module‑Version angeben, z.B. 'latest'
          azPSVersion: latest
          enable-AzPSSession: true
