name: Deploy Sentinel Content

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup PowerShell
      uses: actions/setup-powershell@v2

    - name: Login Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run Sentinel Deployment Script
      shell: pwsh
      run: |
        ./scripts/sen.ps1 `
          -SubscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }} `
          -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP }} `
          -WorkspaceName ${{ secrets.AZURE_WORKSPACE_NAME }} `
          -RepoPath $PWD
