name: Deploy Content to law-sentinel [3a220bc9-6374-4cf3-82c5-df2327485845]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-3a220bc9-6374-4cf3-82c5-df2327485845.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ master ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-3a220bc9-6374-4cf3-82c5-df2327485845.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'rg-sentinel'
      workspaceName: 'law-sentinel'
      workspaceId: 'f373d145-27eb-4bc4-9bbd-f664462beb3e'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule,AutomationRule,Playbook,Workbook,Parser'
      branch: 'master'
      sourceControlId: '3a220bc9-6374-4cf3-82c5-df2327485845'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_3a220bc963744cf382c5df2327485845 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_3a220bc963744cf382c5df2327485845 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_3a220bc963744cf382c5df2327485845 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_3a220bc963744cf382c5df2327485845 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_3a220bc963744cf382c5df2327485845 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_3a220bc963744cf382c5df2327485845 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_3a220bc963744cf382c5df2327485845 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_3a220bc963744cf382c5df2327485845 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_3a220bc963744cf382c5df2327485845 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-3a220bc9-6374-4cf3-82c5-df2327485845.ps1